.TH SURF 1 surf\-VERSION
.SH NAME
surf \- einfacher webkit-basierter Browser
.SH SYNOPSIS
.B surf
.RB [-e\ xid]
.RB [-i]
.RB [-p]
.RB [-s]
.RB [-v]
.RB [-x]
.RB "URI"
.SH BESCHREIBUNG
surf ist ein enifacher Web-Browser basierend auf WebKit/GTK+. Es besteht für ihn die Möglichkeit Webseiten anzuzeigen und Links zu folgen. Er unterstützt das XEmbed-Protokoll welcher es ermöglicht ihn in andere Anwendungen einzubinden. Weiterhin kann surf auf eine andere URI durch Einstellung seiner XProperties gerichtet werden.
.SH OPTIONEN
.TP
.B \-e xid
Reparent ein Fenster spezifiziert durch xid.
.TP
.B \-i
Bilder ausschalten
.TP
.B \-p
Plugins ausschalten
.TP
.B \-s
JavaScript ausschalten
.TP
.B \-v
Gibt die Versions-Information an die Standard-Ausgabe aus und beendet sich dann.
.TP
.B \-x
Gibt xid an die Standard-Ausgabe aus. Dies kann verwendet werden um Script mit dem Browser zu nutzen unter Verwendung von 
.BR xprop(1).
.SH VERWENDUNG
.B Escape
Unterbricht das Laden der gegenwärtigen Seite oder hält den Download an.
.TP
.B STRG\-h
Geht einen Schritt zurück im Verlauf.
.TP
.B STRG\-l
Geht einen Schritt vor im Verlauf.
.TP
.B STRG\-k
Blättert eine Bildschirmseite aufwärts.
.TP
.B STRG\-j
Blättert eine Bildschirmseite abwärts.
.TP
.B STRG\-Umschalten\-k
Vergrößert die Anzeige der Bildschirmseite.
.TP
.B STRG\-Umschalten\-j
Verkleinert die Anzeige der Bildschirmseite.
.TP
.B STRG\-Umschalten\-i
Setzt die Verkleinerung/Vergrößerung der Bildschirmseite zurück auf Normale (100%).
.TP
.B STRG\-s
Öffnet die Such-Leiste.
.TP
.B STRG\-n
Geht zum nächsten Suchergebnis.
.TP
.B STRG\-Umschalten\-n
Geht zum vorhergehenden Suchergebnis.
.TP
.B STRG\-g
Öffnet die URL-Leiste.
.TP
.B STRG\-p
Lädt eine URI aus der primären Auswahl.
.TP
.B STRG\-Umschalten\-p
Öffnet den Druckseiten-Dialog.
.TP
.B STRG\-r
Lädt die Webseite neu unter Verwendung des Caches.
.TP
.B STRG\-Umschalten\-r
Lädt die Webseite neue ohne Verwendung des Caches.
.TP
.B STRG\-y
Kopiert die gegenwärtige URI in die primäre Auswahl.
.TP
.B STRG\-o
Zeigt den Quellcode der gegenwärtigen Seite an.
.SH SIEHE AUCH
.BR dmenu(1)
.BR xprop(1)
.SH FEHLER / BUGS
Bitte teile sie mit!
